### ISSUE TITLE
BlockID: consider including DAHeader 

### ISSUE THREAD

**Issue by Wondertan** [lazyledger/lazyledger-core#242]
Currently, BlockID consists of two fields: actual hash and PartSetHeader, and both of them are going to be changed in some way. Hash will be changed to header hash, while PartSetHeader will be entirely removed. However, I propose not to just remove PartSetHeader but swap it with DAHeader as well. 

First of all, DAHeader is an actual content identifier of Block, as it's the one and only info required to fetch the block, and having Hash of Header as ID simply doesn't make sense from this perspective. However, DAHeader is a problematic structure to be treated as ID because it contains variable value length and it can't be simple printed as a string and used as a map key, thus we need a short form for ID and keeping header/block hash in BlockID would be helpful for such case. In the long-term, this can be solved by introducing a root IPLD node pointing to Rows and Columns from DAHeader and making BlockID a CID of the root node.

Secondary, this would simplify implementation, as that pushes through DAHeader in all the places where BlockID is currently available, avoiding unnecessary changes in funcs and method declarations. The code using BlockId can then be simply updated to rely on either Hash or DAHeader for block identification depending on the requirements as both of those fields are unique for Block.

**Comment by marbar3778** [comment]
BlockID will be removed entirely in the near future, I recently add headerHash to the commit in preparation for this. I would say this is better than filling blockID with new data.

**Comment by Wondertan** [comment]
@marbar3778, @liamsi, can you pls explain the motivation behind full BlockID removal? #184 mentions simplifications that I might misunderstand as something like `type BlockID headerHash`, but not the entire removal. Also, I thought that BlockID would be kept in the codebase anyway to simply identify the block, but now I guess that the motivation is to lesser use Block concept in favor of Header, e.g. BlockPool -> HeaderPool, BlockStore -> HeaderStore, BlockID -> HeaderHash. Is it close to the truth?

**Comment by liamsi** [comment]
So first of all independent of lazyledger, the BlockID including PartSetHeader is something that should be reconsidered: https://github.com/tendermint/spec/issues/78

>  #184 mentions simplifications that I might misunderstand as something like type BlockID headerHash, but not the entire removal.

Sorry if #184 is confusing. I tried to write down how essentially replace BlockID with the header hash and the DAHeader. The DAHeader replaces PartSetHeader and the hash inside gets moved into the header instead (and becomes a simple hash instead of merkelizing the header fields [as currently ](https://github.com/tendermint/tendermint/blob/99c73dd3c116e261816532d957aa95e2d38e9985/types/block.go#L448)).

> Also, I thought that BlockID would be kept in the codebase anyway to simply identify the block,

A header hash also fully identifies the block. Additionally, the data root fully identifies the Block.Data.

> but now I guess that the motivation is to lesser use Block concept in favor of Header, e.g. BlockPool -> HeaderPool, BlockStore -> HeaderStore, BlockID -> HeaderHash. Is it close to the truth?

Yeah, the Header is more important in LazyLedger. That is because Header + DAHeader is everything a node needs to get very high assurance about the chain they are observing. Even most fullnodes will likely just do that instead of following the whole Blocks (as fullnodes do in other blockchains). You can think of these nodes as light-clients that additionally do Data Availability checks.
Note that eventually, the header inside this repository will look like:
https://github.com/lazyledger/lazyledger-specs/blob/master/specs/data_structures.md#header
I've tried to chunk this up into smaller parts of work. Maybe that's what was confusing in that issue (#184). I'll try to improve it with your feedback.

BTW @adlerjohn did a good writeup on the different node types in lazyledger. It explains who need to download what with which security assumptions: https://github.com/lazyledger/lazyledger-specs/blob/master/specs/node_types.md

**Comment by liamsi** [comment]
@Wondertan does this comment make it a bit clearer on howto proceed: https://github.com/lazyledger/lazyledger-core/pull/205#issuecomment-804292134 ?

**Comment by Wondertan** [comment]
@liamsi, Yes!

**Comment by Wondertan** [comment]
Also, the issue is resolved so closing
