### ISSUE TITLE
Add `availableDataOriginalSharesUsed` to Header

### ISSUE THREAD

**Issue by Wondertan** [lazyledger/lazyledger-core#249]
Specs [state](https://github.com/lazyledger/lazyledger-specs/blob/master/specs/data_structures.md#header) that `availableDataOriginalSharesUsed` have to be part of the Header. Current Header implementation misses that

**Comment by liamsi** [comment]
@adlerjohn would `availableDataOriginalSharesUsed` according to the spec is 
> The number of shares used in the original data square that are not tail padding.

Should we extend `ComputeShares()` to return an `int` that tells the caller how many shares are actually `tailShares` s.t. it can be used to set `availableDataOriginalSharesUsed` in the header?

And how important is it to subtract the tailShares from `availableDataOriginalSharesUsed`? Isn't it mostly an optimization?

**Comment by adlerjohn** [comment]
> Should we extend `ComputeShares()` to return an `int` that tells the caller how many shares are actually `tailShares` s.t. it can be used to set `availableDataOriginalSharesUsed` in the header?

Not a bad idea.

> how important is it to subtract the `len(tailShares)` from `availableDataOriginalSharesUsed`? Isn't it mostly an optimization?

It is an optimization, but it enables potentially significant savings. Since block sizes grow by multiples of 4, it can often be the case that there's a bunch of empty space in the original data square. Up to ~3/8th of the EDS can be "known" and thus doesn't have to be sampled or have row erasure coding computed.
