### ISSUE TITLE
Arrange available data in shares according to spec

### ISSUE THREAD

**Issue by liamsi** [lazyledger/lazyledger-core#38]
Before implementing the erasure coding of the data itself (see #23), we need to arrange the data into a square matrix to do so. A naive approach would be to split the data in same sized shares and order that into a matrix. It would be better to implement this directly by following the message layout of the spec s.t. the implementation evolves closer to the spec and potentially inform give feedback for the spec itself. 

Specification:  https://github.com/lazyledger/lazyledger-specs/blob/master/specs/data_structures.md#arranging-available-data-into-shares
Rationale document: https://github.com/lazyledger/lazyledger-specs/blob/master/rationale/message_block_layout.md

ref: https://github.com/lazyledger/lazyledger-specs/issues/69

**Comment by musalbas** [comment]
The rsmt2d library expects a flattened slice of shares, as the library arranges it into a square for you.

In order to enforce a particular layout, one could arrange it as wanted before flatenning it and passing it to the library. Either way the message layout specified in the spec isn't consensus critical.

**Comment by liamsi** [comment]
closing in favour of #234 which has more details.
